"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = ['icons/pyPickyPixelsIcon.icns','icons/pyPickyPixelsIcon.png']
OPTIONS = {'iconfile': 'icons/pyPickyPixelsIcon.icns',
            'includes': ['pySimpleGUI','cv2','shutil','os','base64','urllib'] }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
