"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = ['/Users/lukasunguraitis/Documents/5 Vault/GitHub/pyPickyPixels/icons/pyPickyPixelsIcon.icns']
OPTIONS = {'iconfile': '/Users/lukasunguraitis/Documents/5 '
             'Vault/GitHub/pyPickyPixels/icons/pyPickyPixelsIcon.icns',
            'includes': ['pySimpleGUI','cv2','shutil','os'] }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
